// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"waf/internal/dao/internal"
)

// internalAppDao is internal type for wrapping internal DAO implements.
type internalAppDao = *internal.AppDao

// appDao is the data access object for table app.
// You can define custom methods on it to extend its functionality as you wish.
type appDao struct {
	internalAppDao
}

var (
	// App is globally public accessible object for table app operations.
	App = appDao{
		internal.NewAppDao(),
	}
)

// Fill with you ideas below.
