// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"waf/internal/dao/internal"
)

// internalIpDao is internal type for wrapping internal DAO implements.
type internalIpDao = *internal.IpDao

// ipDao is the data access object for table ip.
// You can define custom methods on it to extend its functionality as you wish.
type ipDao struct {
	internalIpDao
}

var (
	// Ip is globally public accessible object for table ip operations.
	Ip = ipDao{
		internal.NewIpDao(),
	}
)

// Fill with you ideas below.
