// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Ip is the golang structure of table ip for DAO operations like Where/Data.
type Ip struct {
	g.Meta     `orm:"table:ip, do:true"`
	Id         interface{} //
	Ip         interface{} //
	Action     interface{} //
	ExpireTime interface{} //
	Domain     interface{} //
	AddReason  interface{} //
	CreateTime *gtime.Time //
}
