// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Page is the golang structure of table page for DAO operations like Where/Data.
type Page struct {
	g.Meta     `orm:"table:page, do:true"`
	Id         interface{} //
	Domain     interface{} //
	Action     interface{} //
	Uri        interface{} //
	Method     interface{} //
	AddReason  interface{} //
	CreateTime *gtime.Time //
	UpdateTime *gtime.Time //
}
