// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Rule is the golang structure of table rule for DAO operations like Where/Data.
type Rule struct {
	g.Meta      `orm:"table:rule, do:true"`
	Ruleid      interface{} //
	Name        interface{} //
	Key         interface{} //
	Action      interface{} //
	Vuln        interface{} //
	Level       interface{} //
	RuleContent interface{} //
	Ct          interface{} //
	Status      interface{} //
	CreateTime  *gtime.Time //
	UpdateTime  *gtime.Time //
}
