// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Vuln is the golang structure of table vuln for DAO operations like Where/Data.
type Vuln struct {
	g.Meta     `orm:"table:vuln, do:true"`
	Id         interface{} //
	Name       interface{} //
	Key        interface{} //
	CreateTime *gtime.Time //
	UpdateTime *gtime.Time //
}
