// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Ip is the golang structure for table ip.
type Ip struct {
	Id         int         `json:"id"         description:""`
	Ip         string      `json:"ip"         description:""`
	Action     string      `json:"action"     description:""`
	ExpireTime int64       `json:"expireTime" description:""`
	Domain     string      `json:"domain"     description:""`
	AddReason  string      `json:"addReason"  description:""`
	CreateTime *gtime.Time `json:"createTime" description:""`
}
