// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Rule is the golang structure for table rule.
type Rule struct {
	Ruleid      string      `json:"ruleid"      description:""`
	Name        string      `json:"name"        description:""`
	Key         string      `json:"key"         description:""`
	Action      string      `json:"action"      description:""`
	Vuln        string      `json:"vuln"        description:""`
	Level       string      `json:"level"       description:""`
	RuleContent string      `json:"ruleContent" description:""`
	Ct          string      `json:"ct"          description:""`
	Status      string      `json:"status"      description:""`
	CreateTime  *gtime.Time `json:"createTime"  description:""`
	UpdateTime  *gtime.Time `json:"updateTime"  description:""`
}
