// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Setting is the golang structure for table setting.
type Setting struct {
	Id    int    `json:"id"    description:""`
	Group string `json:"group" description:""`
	Key   string `json:"key"   description:""`
	Value string `json:"value" description:""`
}
